### ISSUE TITLE
Standard Commands and Commands Repository Modelation

### ISSUE THREAD

**Issue by MiguelMDSDP** [furgbol/ai#1]
Para uma unificação da forma de geração de comandos para todo o sistema, foi desenvolvido um protocolo padrão de comandos que serão armazenados em um repositório para serem enviados para fora do nosso sistema.

A implementação desta modelagem foi feita de acordo com o diagrama de classes abaixo:
![Command_Repository_Class_Diagram](https://user-images.githubusercontent.com/31577199/74787275-86950180-528d-11ea-90a4-5ec825eff8ba.jpg)

**Comment by MiguelMDSDP** [comment]
Testing slack integration.

**Comment by renantarouco** [comment]
Vai atualizar a issue ou já vai fechar ela?
