### ISSUE TITLE
Drivers ZMQ

### ISSUE THREAD

**Issue by MiguelMDSDP** [furgbol/ai#14]
Criação do pacote para comunicação com o VSS-Core usando a biblioteca ZeroMQ.

**Comment by wellingtonfs** [comment]
Foi finalizado o módulo que faz a comunicação da Ai do furgbol com o VSS-Simulator.

Este pacote usa a biblioteca ZMQ para que nosso sistema troque dados com o VSS-Simulator, já que essa é a mesma biblioteca usada no VSS-Core.

A estrutura deste pacote é muito parecida com a estrutura do pacote de comunicação UDP, ambos contém funções para criação do socket, envio de dados, recebimento de dados e fechamento da conexão.

Essa biblioteca usa o sistema publish/subscribe, onde vários clientes trocam dados publicando (publishers) e lendo (subscribes) em tópicos específicos. É usado o protocolo TCP para a troca de dados.

**Comment by MiguelMDSDP** [comment]
Resolvido em #13
