### ISSUE TITLE
World Model Implementation

### ISSUE THREAD

**Issue by MiguelMDSDP** [furgbol/ai#4]
Para um melhor controle do nosso ambiente de jogo, é necessário um módulo que proporcione uma aproximação do mundo real ao nosso sistema, simulando-o com clareza e pertinência. O modelo mundo é o responsável por fazer isso, modelando todos os aspectos do mundo real.

Este módulo precisa ser implementado com base no diagrama de classes abaixo:
![World Model Class Diagram](https://user-images.githubusercontent.com/31577199/74892836-7c483580-5369-11ea-93a8-26b3437a3a53.jpg)

**Comment by renantarouco** [comment]
Na ligação do _Robot_ com _Pose_, pelo que vi por aí, deve haver duas setas de composição, uma pro _currentPosition_ e outra pro _targetPosition_.

**Comment by MiguelMDSDP** [comment]
@renantarouco arrumado!

**Comment by renantarouco** [comment]
Acho que já podemos fechar aqui então. Assim que ressurgir alguma coisa nova abrimos uma issue. que tal?

**Comment by MiguelMDSDP** [comment]
Perfeito.
