### ISSUE TITLE
UDP Communication Drivers

### ISSUE THREAD

**Issue by MiguelMDSDP** [furgbol/ai#5]
A comunicação via UDP é muito utilizada em todo o sistema, portanto é demandada a implementação de serviços de recebimento e envio de dados através deste protocolo.

**Comment by wellingtonfs** [comment]
- [x] Criação do pacote
- [x] Atualização do README interno
- [x] Implementação das funções
- [x] Teste das funcionalidades
- [x] Revisão
- [x] Pull Request
