### ISSUE TITLE
Simulator Commands Modelation

### ISSUE THREAD

**Issue by MiguelMDSDP** [furgbol/ai#7]
Assim como nosso sistema possui um comando padrão, o simulador que está sendo utilizado também utiliza comandos próprios que devem ser modelados para conseguirmos uma manipulação melhor do mesmo.

**Comment by renantarouco** [comment]
@brunolobell pode dar uma atualizada por aqui. O que tu pesquisou e em que ponto tu estás agora?

**Comment by brunolobell** [comment]
Em relação ao simulador, eu pesquisei sobre os comandos básico, comandos de configuração e os comandos de comunicação, que são utilizado pelo mesmo. Agora estou fazendo o diagrama de classe, ao terminar atualizo o README.

**Comment by MiguelMDSDP** [comment]
Issue resolvida: #12.
