### ISSUE TITLE
Protobuf Parsers

### ISSUE THREAD

**Issue by MiguelMDSDP** [furgbol/ai#9]
Os dados que são utilizados em nosso sistema são heterogêneos, portanto algumas transformações precisam ser feitas com os mesmos. Este caso acontece com a comunicação do nosso sistema com o [Simulador do VSS SDK](https://github.com/VSS-SDK/VSS-Simulator), pois os dados no simulador são [protobufs](https://developers.google.com/protocol-buffers) e em nosso sistema são tipos escritos em Golang.

**Comment by wellingtonfs** [comment]
- [x] Transformação de protobuf padrão do simulador para modelagem do mundo
- [x] Transformação de comandos do simulador modelados no software para protobuf padrão do simulador

**Comment by wellingtonfs** [comment]
Foram implementados parses para:

- Comando Simulador -> Protobuf Comando Simulador
- Protobuf State Simulador -> Modelo Mundo
- Protobuf Control VSS-Viewer -> Control

**Comment by MiguelMDSDP** [comment]
Resolvido em #13
